insert into tipo_productos(descrip)VALUES("Canasta Basica");
insert into tipo_productos(descrip)VALUES("Productos Lapteos");
insert into tipo_productos(descrip)VALUES("Refrescos");
insert into tipo_productos(descrip)VALUES("Jugos");
insert into tipo_productos(descrip)VALUES("Panaderia");
insert into tipo_productos(descrip)VALUES("Enbutidos");
insert into tipo_productos(descrip)VALUES("Pescados");
insert into tipo_productos(descrip)VALUES("Productos Enlatados");
insert into tipo_productos(descrip)VALUES("Cereales");
insert into tipo_productos(descrip)VALUES("Bebidas Alcoholicas");
insert into tipo_productos(descrip)VALUES("Granos");
insert into tipo_productos(descrip)VALUES("Dulces");
insert into tipo_productos(descrip)VALUES("Cigarrillos");